//thunk
export const FETCH_BOOKS_DATA='books/fetchBooks/get'
export const POST_ADD_BOOK_DATA='books/addbook/post'
export const DELETE_BOOK_DATA='book/deletebook/delete'
export const PUT_UPDATE_BOOK_DATA ='book/updatebook/put'
export const GET_BOOK_DATA_BY_ID='book/fetchBookbyID/get'






//saga
export const FETCH_BOOKS_DATA_PENDING = 'FETCH_BOOKS_DATA_PENDING';
export const FETCH_BOOKS_DATA_FULFILLED = 'FETCH_BOOKS_DATA_FULFILLED';
export const FETCH_BOOKS_DATA_REJECTED = 'FETCH_BOOKS_DATA_REJECTED';

export const GET_BOOK_DATA_BY_ID_PENDING = 'GET_BOOK_DATA_BY_ID_PENDING';
export const GET_BOOK_DATA_BY_ID_FULFILLED = 'GET_BOOK_DATA_BY_ID_FULFILLED';
export const GET_BOOK_DATA_BY_ID_REJECTED = 'GET_BOOK_DATA_BY_ID_REJECTED';

export const POST_ADD_BOOK_DATA_PENDING = 'POST_ADD_BOOK_DATA_PENDING';
export const POST_ADD_BOOK_DATA_FULFILLED = 'POST_ADD_BOOK_DATA_FULFILLED';
export const POST_ADD_BOOK_DATA_REJECTED = 'POST_ADD_BOOK_DATA_REJECTED';

export const DELETE_BOOK_DATA_PENDING = 'DELETE_BOOK_DATA_PENDING';
export const DELETE_BOOK_DATA_FULFILLED = 'DELETE_BOOK_DATA_FULFILLED';
export const DELETE_BOOK_DATA_REJECTED = 'DELETE_BOOK_DATA_REJECTED';

export const PUT_UPDATE_BOOK_DATA_PENDING = 'PUT_UPDATE_BOOK_DATA_PENDING';
export const PUT_UPDATE_BOOK_DATA_FULFILLED = 'PUT_UPDATE_BOOK_DATA_FULFILLED';
export const PUT_UPDATE_BOOK_DATA_REJECTED = 'PUT_UPDATE_BOOK_DATA_REJECTED';
